version: '3.9'
services:

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
      args:
        - biuldno=0.8
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ps_user
      - POSTGRES_PASSWORD=ps_password
      - POSTGRES_DB=password

volumes:
  static_value:
  media_value:
  postgres_data:
