# Generated by Django 4.2.2 on 2023-07-09 01:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hebrew', models.CharField(max_length=15)),
                ('english', models.CharField(max_length=15)),
                ('russian', models.CharField(max_length=15)),
                ('frequency', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('part_of_speech', models.CharField(choices=[('NOUN', 'noun'), ('VERB', 'verb'), ('ADJ', 'adjective'), ('PREPOSITION', 'preposition'), ('PRONOUN', 'pronoun')], max_length=15)),
                ('tags', models.ManyToManyField(blank=True, to='word.tag')),
            ],
        ),
        migrations.CreateModel(
            name='WordStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timesShown', models.IntegerField()),
                ('timesCorrect', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(choices=[('ROOT', 'root'), ('VERB_CATEGORY', 'verb category'), ('GENDER', 'gender'), ('PREP_AFTER', 'prep_after')], max_length=15)),
                ('value', models.CharField(max_length=10)),
                ('words', models.ManyToManyField(related_name='words', to='word.word')),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='users_statistics',
            field=models.ManyToManyField(through='word.WordStatistics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_collections', to=settings.AUTH_USER_MODEL)),
                ('users_using', models.ManyToManyField(blank=True, related_name='used_collections', to=settings.AUTH_USER_MODEL)),
                ('words', models.ManyToManyField(related_name='collections', to='word.word')),
            ],
        ),
    ]
